export const humanSystems = [
  {
    id: "1",
    name_system: "Скелетная система",
    content_system: [],
    img_system: "https://svgshare.com/i/YM9.svg",
    img_system_alt: "Скелетная  система",
    path: "/skeleton",
  },
  {
    id: "2",
    name_system: "Сердечно-сосудистая система",
    content_system: [],
    img_system: "https://svgshare.com/i/YLY.svg",
    img_system_alt: "Сердечно-сосудистая система",
    path: "/heart",
  },
  {
    id: "3",
    name_system: "Пищеварительная система",
    content_system: [],
    img_system: "https://svgshare.com/i/YL6.svg",
    img_system_alt: "Пищеварительная система",
    path: "/digestion",
  },
  {
    id: "4",
    name_system: "Нервная система",
    content_system: [],
    img_system: "https://svgshare.com/i/YL7.svg",
    img_system_alt: "Нервная система",
    path: "/nerves",
  },
  {
    id: "5",
    name_system: "Мышечная система",
    content_system: [],
    img_system: "https://svgshare.com/i/YKa.svg",
    img_system_alt: "Мышечная система",
    path: "/muscles",
  },
  {
    id: "6",
    name_system: "Дыхательная система",
    content_system: [],
    img_system: "https://svgshare.com/i/YK6.svg",
    img_system_alt: "Дыхательная система",
    path: "/breathing",
  },
];
